### ISSUE TITLE
Copying in Erlang cookie from local machine to container

### ISSUE THREAD

**Issue by Brian-Elliott** [harbur/docker-rabbitmq-cluster#8]
Am I wrong to think having the erlang cookie in the yml would not be safe for production? Is there an alternative that you would recommend?

**Comment by dkapanidis** [comment]
Yes that's a valid point, this repo was created before the [Docker secrets](https://docs.docker.com/engine/swarm/secrets/) were available.

For sensitive data, secrets are more appropriate than environment variables, though take note that secrets are only available to swarm mode not standalone containers.

Nowadays it is considered best-practice to use secrets for sensitive data, though for compatibility reasons (and maybe ease of use in development) you'll even see official packages (e.g. [mysql](https://hub.docker.com/_/mysql/) ) to keep using env variables but also support secrets in files.

An option to configure sensitive data with secrets can be seen at mysql [entrypoint](https://github.com/docker-library/mysql/blob/6c414e7f38c2079c7193beae5dc7c34ee46cd6e7/8.0/docker-entrypoint.sh#L21#L41). PRs are welcome if you're interested in adding the option.

**Comment by Brian-Elliott** [comment]
Ya, we're actually using Kubernetes on top so we started putting secrets in there. Thank you.
